# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\life\python\order_1\119_2023_02_15_pic_pairing\pic_pairing.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import os
from PyQt5 import QtCore, QtGui, QtWidgets
import image_rc

class Ui_MainWindow(object):
    def setupUi(self, Object):
        Object.setObjectName("Object")
        Object.resize(1119, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Object.sizePolicy().hasHeightForWidth())
        Object.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Object.setWindowIcon(icon)
        Object.setStyleSheet("font: 75 8pt \"微软雅黑\";")
        self.centralwidget = QtWidgets.QWidget(Object)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 9, 521, 511))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 480, 480))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 10, 521, 511))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 480, 480))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 550, 171, 23))
        self.pushButton.setObjectName("pushButton")
        self.labelimage = QtWidgets.QLabel(self.centralwidget)
        self.labelimage.setGeometry(QtCore.QRect(85, 525, 55, 55))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.labelimage.setFont(font)
        self.labelimage.setText("")
        self.labelimage.setScaledContents(True)
        self.labelimage.setObjectName("labelimage")
         #添加图片
        cover_img = os.path.abspath('D:\python\homework\文件夹.png')
        image = QtGui.QPixmap(cover_img).scaled(1200, 1200)
        self.labelimage.setPixmap(image)
        self.labelimage.setScaledContents(True)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 550, 171, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        Object.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Object)
        self.statusbar.setObjectName("statusbar")
        Object.setStatusBar(self.statusbar)

        self.retranslateUi(Object)
        QtCore.QMetaObject.connectSlotsByName(Object)

    def retranslateUi(self, Object):
        _translate = QtCore.QCoreApplication.translate
        Object.setWindowTitle(_translate("Object", "染色体分类系统"))
        self.groupBox.setTitle(_translate("Object", "原始图片"))
        self.groupBox_2.setTitle(_translate("Object", "排序"))
        self.pushButton.setText(_translate("Object", "选择图片路径"))
        self.pushButton_2.setText(_translate("Object", "排序"))

